// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: proto/log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeverityNumber int32

const (
	SeverityNumber_SEVERITY_UNSPECIFIED SeverityNumber = 0
	SeverityNumber_TRACE                SeverityNumber = 1
	SeverityNumber_DEBUG                SeverityNumber = 5
	SeverityNumber_INFO                 SeverityNumber = 9
	SeverityNumber_WARN                 SeverityNumber = 13
	SeverityNumber_ERROR                SeverityNumber = 17
	SeverityNumber_FATAL                SeverityNumber = 21
)

// Enum value maps for SeverityNumber.
var (
	SeverityNumber_name = map[int32]string{
		0:  "SEVERITY_UNSPECIFIED",
		1:  "TRACE",
		5:  "DEBUG",
		9:  "INFO",
		13: "WARN",
		17: "ERROR",
		21: "FATAL",
	}
	SeverityNumber_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"TRACE":                1,
		"DEBUG":                5,
		"INFO":                 9,
		"WARN":                 13,
		"ERROR":                17,
		"FATAL":                21,
	}
)

func (x SeverityNumber) Enum() *SeverityNumber {
	p := new(SeverityNumber)
	*p = x
	return p
}

func (x SeverityNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeverityNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_log_proto_enumTypes[0].Descriptor()
}

func (SeverityNumber) Type() protoreflect.EnumType {
	return &file_proto_log_proto_enumTypes[0]
}

func (x SeverityNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeverityNumber.Descriptor instead.
func (SeverityNumber) EnumDescriptor() ([]byte, []int) {
	return file_proto_log_proto_rawDescGZIP(), []int{0}
}

type EventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixNano  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Severity      SeverityNumber         `protobuf:"varint,2,opt,name=severity,proto3,enum=logs_gateway_service.SeverityNumber" json:"severity,omitempty"`
	SeverityText  string                 `protobuf:"bytes,3,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MetaErr       string                 `protobuf:"bytes,8,opt,name=meta_err,json=metaErr,proto3" json:"meta_err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_proto_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_proto_log_proto_rawDescGZIP(), []int{0}
}

func (x *EventLog) GetTimeUnixNano() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeUnixNano
	}
	return nil
}

func (x *EventLog) GetSeverity() SeverityNumber {
	if x != nil {
		return x.Severity
	}
	return SeverityNumber_SEVERITY_UNSPECIFIED
}

func (x *EventLog) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *EventLog) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EventLog) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EventLog) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *EventLog) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EventLog) GetMetaErr() string {
	if x != nil {
		return x.MetaErr
	}
	return ""
}

type SysLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixNano  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Severity      SeverityNumber         `protobuf:"varint,2,opt,name=severity,proto3,enum=logs_gateway_service.SeverityNumber" json:"severity,omitempty"`
	SeverityText  string                 `protobuf:"bytes,3,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysLog) Reset() {
	*x = SysLog{}
	mi := &file_proto_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysLog) ProtoMessage() {}

func (x *SysLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysLog.ProtoReflect.Descriptor instead.
func (*SysLog) Descriptor() ([]byte, []int) {
	return file_proto_log_proto_rawDescGZIP(), []int{1}
}

func (x *SysLog) GetTimeUnixNano() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeUnixNano
	}
	return nil
}

func (x *SysLog) GetSeverity() SeverityNumber {
	if x != nil {
		return x.Severity
	}
	return SeverityNumber_SEVERITY_UNSPECIFIED
}

func (x *SysLog) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *SysLog) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SysLog) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SysLog) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_log_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_log_proto protoreflect.FileDescriptor

const file_proto_log_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/log.proto\x12\x14logs_gateway_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x03\n" +
	"\bEventLog\x12@\n" +
	"\x0etime_unix_nano\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeUnixNano\x12@\n" +
	"\bseverity\x18\x02 \x01(\x0e2$.logs_gateway_service.SeverityNumberR\bseverity\x12#\n" +
	"\rseverity_text\x18\x03 \x01(\tR\fseverityText\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12N\n" +
	"\n" +
	"attributes\x18\a \x03(\v2..logs_gateway_service.EventLog.AttributesEntryR\n" +
	"attributes\x12\x19\n" +
	"\bmeta_err\x18\b \x01(\tR\ametaErr\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x06SysLog\x12@\n" +
	"\x0etime_unix_nano\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeUnixNano\x12@\n" +
	"\bseverity\x18\x02 \x01(\x0e2$.logs_gateway_service.SeverityNumberR\bseverity\x12#\n" +
	"\rseverity_text\x18\x03 \x01(\tR\fseverityText\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*j\n" +
	"\x0eSeverityNumber\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05TRACE\x10\x01\x12\t\n" +
	"\x05DEBUG\x10\x05\x12\b\n" +
	"\x04INFO\x10\t\x12\b\n" +
	"\x04WARN\x10\r\x12\t\n" +
	"\x05ERROR\x10\x11\x12\t\n" +
	"\x05FATAL\x10\x152\xa2\x01\n" +
	"\aRequest\x12K\n" +
	"\tSendEvent\x12\x1e.logs_gateway_service.EventLog\x1a\x1e.logs_gateway_service.Response\x12J\n" +
	"\n" +
	"SendSysLog\x12\x1c.logs_gateway_service.SysLog\x1a\x1e.logs_gateway_service.ResponseB\x13Z\x11MidasEdgeV2/pb;pbb\x06proto3"

var (
	file_proto_log_proto_rawDescOnce sync.Once
	file_proto_log_proto_rawDescData []byte
)

func file_proto_log_proto_rawDescGZIP() []byte {
	file_proto_log_proto_rawDescOnce.Do(func() {
		file_proto_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_log_proto_rawDesc), len(file_proto_log_proto_rawDesc)))
	})
	return file_proto_log_proto_rawDescData
}

var file_proto_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_log_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_log_proto_goTypes = []any{
	(SeverityNumber)(0),           // 0: logs_gateway_service.SeverityNumber
	(*EventLog)(nil),              // 1: logs_gateway_service.EventLog
	(*SysLog)(nil),                // 2: logs_gateway_service.SysLog
	(*Response)(nil),              // 3: logs_gateway_service.Response
	nil,                           // 4: logs_gateway_service.EventLog.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_log_proto_depIdxs = []int32{
	5, // 0: logs_gateway_service.EventLog.time_unix_nano:type_name -> google.protobuf.Timestamp
	0, // 1: logs_gateway_service.EventLog.severity:type_name -> logs_gateway_service.SeverityNumber
	4, // 2: logs_gateway_service.EventLog.attributes:type_name -> logs_gateway_service.EventLog.AttributesEntry
	5, // 3: logs_gateway_service.SysLog.time_unix_nano:type_name -> google.protobuf.Timestamp
	0, // 4: logs_gateway_service.SysLog.severity:type_name -> logs_gateway_service.SeverityNumber
	1, // 5: logs_gateway_service.Request.SendEvent:input_type -> logs_gateway_service.EventLog
	2, // 6: logs_gateway_service.Request.SendSysLog:input_type -> logs_gateway_service.SysLog
	3, // 7: logs_gateway_service.Request.SendEvent:output_type -> logs_gateway_service.Response
	3, // 8: logs_gateway_service.Request.SendSysLog:output_type -> logs_gateway_service.Response
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_log_proto_init() }
func file_proto_log_proto_init() {
	if File_proto_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_log_proto_rawDesc), len(file_proto_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_log_proto_goTypes,
		DependencyIndexes: file_proto_log_proto_depIdxs,
		EnumInfos:         file_proto_log_proto_enumTypes,
		MessageInfos:      file_proto_log_proto_msgTypes,
	}.Build()
	File_proto_log_proto = out.File
	file_proto_log_proto_goTypes = nil
	file_proto_log_proto_depIdxs = nil
}
